import { Inter } from "next/font/google";
import Navbar from "../admin/components_admin/Navbar";
import Sidebar from "../admin/components_admin/Sidebar";

// import "../globals.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

function RootLayout({ children }) {
    return (
        <html lang="en">
            <head>
            </head>
            <link rel="shortcut icon" href="assets/images/favicon.ico" />



            {/* dropzone css */}
            <link rel="stylesheet" href="assets/libs/dropzone/dropzone.css" type="text/css" />
            {/* Filepond css */}
            <link rel="stylesheet" href="assets/libs/filepond/filepond.min.css" type="text/css" />
            <link rel="stylesheet" href="assets/libs/filepond-plugin-image-preview/filepond-plugin-image-preview.min.css" />
            {/* Layout config Js */}
            {/* Bootstrap Css */}
            <link href="assets/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
            {/* Icons Css */}
            <link href="assets/css/icons.min.css" rel="stylesheet" type="text/css" />
            {/* App Css*/}
            <link href="assets/css/app.min.css" rel="stylesheet" type="text/css" />
            {/* custom Css*/}
            <link href="assets/css/custom.min.css" rel="stylesheet" type="text/css" />



            <body className={inter.className}>
                <div id="layout-wrapper">
                    <Navbar />
                    <Sidebar />
                    <div class="vertical-overlay"></div>
                    <div className="main-content">
                        <div className="page-content">
                            <div className="container-fluid">
                                {children}
                            </div>
                            {/* container-fluid */}
                        </div>
                        {/* End Page-content */}
                        <footer className="footer">
                            <div className="container-fluid">
                                <div className="row">
                                    <div className="col-sm-6">
                                        @Brand ME
                                    </div>
                                    <div className="col-sm-6">
                                        <div className="text-sm-end d-none d-sm-block">
                                            Design &amp; Develop by BRAND ME Technologies pvt ltd
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </footer>
                    </div>


                </div>
                <div>
                    {/*start back-to-top*/}
                    <button onclick="topFunction()" className="btn btn-danger btn-icon" id="back-to-top">
                        <i className="ri-arrow-up-line" />
                    </button>
                    {/*end back-to-top*/}
                    {/*preloader*/}
                    {/* <div id="preloader">
                        <div id="status">
                            <div className="spinner-border text-primary avatar-sm" role="status">
                                <span className="visually-hidden">Loading...</span>
                            </div>
                        </div>
                    </div> */}
                </div>



                {/* JAVASCRIPT */}

                <script src="assets/libs/bootstrap/js/bootstrap.bundle.min.js"></script>
                <script src="assets/libs/simplebar/simplebar.min.js"></script>
                <script src="assets/libs/node-waves/waves.min.js"></script>
                <script src="assets/libs/feather-icons/feather.min.js"></script>
                <script src="assets/js/pages/plugins/lord-icon-2.1.0.js"></script>
                <script src="assets/js/plugins.js"></script>

                {/* apexcharts */}

                <script src="assets/libs/apexcharts/apexcharts.min.js"></script>

                {/* Vector map*/}

                <script src="assets/libs/jsvectormap/js/jsvectormap.min.js"></script>
                <script src="assets/libs/jsvectormap/maps/world-merc.js"></script>

                {/*Swiper slider js*/}

                <script src="assets/libs/swiper/swiper-bundle.min.js"></script>

                {/* Dashboard init */}

                <script src="assets/js/pages/dashboard-ecommerce.init.js"></script>

                {/* App js */}

                <script src="assets/js/app.js"></script>
            </body>
        </html>
    );
}
export default RootLayout